eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8762
spring:
  application:
    name: service-provider


#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/javashop
#    driver-class-name: com.mysql.jdbc.Driver
#  http:
#    encoding:
#      charset: utf-8
#      enabled: true
#mybatis:
#  type-aliases-package: com.developlee.mybatispagehelper.domain
#  mapper-locations: classpath:/mapper/*.xml
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

  jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy